### ISSUE TITLE
Not working on Xcode 6.1

### ISSUE THREAD

**Issue by DoctorG** [rickytan/RTImageAssets#17]
I would love this great tool to function, but I can't get it to work -- either installed from Alcatraz or directly from download from github. 

I don't know how I can troubleshoot to help figure out why it won't work.  

Any ideas, Ricky? 

PS.  Thanks for spending time on this great idea and sharing with all!

**Comment by rickytan** [comment]
#2 maybe helpful

**Comment by DoctorG** [comment]
C4A681B0-4A26-480E-93EC-1218098B9AA0

**Comment by rickytan** [comment]
This UUID has already added to the plugin compatibility list, so it may due to other issues.

Can you open the `Settings` window at **File**->**ImageAssets**->**Settings** ?

**Comment by DoctorG** [comment]
No, I can’t.

**Comment by rickytan** [comment]
Is other Plugins works fine?

**Comment by DoctorG** [comment]
Yes all others are fine. I have the menu items but nothing happens.

**Comment by rad182** [comment]
I too having same issue. Any workaround at the moment?

**Comment by sammy-SC** [comment]
my uuid "A16FF353-8441-459E-A50C-B071F53F51B7" is in the compatibility list, I can open settings window and all other plugins work fine. However when I press generate missing assets nothing seems to happen.

**Comment by miversen** [comment]
I couldn't make it work either. Everytime I pressed "Generate Missing Images" it did not do anything. I decided to debug it (see how on http://www.blackdogfoundry.com/blog/debugging-your-xcode-plugin/) and found out that the reason is that the plugin expects your asset folder to be located in the "Current Working Directory".

Easy solution: Move the assets folder to the "Current Working Directory"

Fix to the plugin: Make a recursive search through the entire solution to locate the assets folder.

**Comment by rickytan** [comment]
Thanks @miversen , but in fact I did that on purpose, because in some cases your project relies on other projects, and they may have their own assets, I just don't want to change those assets not belong to me.

Could you please send a pull request ?

**Comment by miversen** [comment]
@rickytan I did not change any code, I solved it by moving the assets folder. I like your thought about not changing anything else unintented so maybe a solution could be to provide the user with feedback so he knows that the problem is the assets folder location?
